# Generated by Django 4.0.3 on 2022-04-16 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('num_of_adults', models.IntegerField(default=0)),
                ('num_of_children', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='tour',
            name='customer',
            field=models.ManyToManyField(through='tourapp.BookTour', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour',
            name='departure_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='tour',
            name='price_for_adults',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='price_for_children',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='home_town',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booktour',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapp.tour'),
        ),
        migrations.AddField(
            model_name='booktour',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
