# Generated by Django 4.0.3 on 2022-04-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='note',
        ),
        migrations.AddField(
            model_name='tour',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
