# Generated by Django 4.0.3 on 2022-04-30 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_remove_tour_note_tour_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentnews',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='travelapp.news'),
        ),
        migrations.AddField(
            model_name='commenttour',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='travelapp.tour'),
        ),
        migrations.AddField(
            model_name='like',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='travelapp.news'),
        ),
        migrations.AddField(
            model_name='rate',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='travelapp.tour'),
        ),
    ]
