# Generated by Django 4.0.3 on 2022-05-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0013_alter_news_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booktour',
            unique_together={('user', 'tour')},
        ),
    ]
