# Generated by Django 4.0.3 on 2022-05-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0015_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktour',
            name='send_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tag',
            field=models.ManyToManyField(related_name='tours', to='travelapp.tag'),
        ),
    ]
