# Generated by Django 4.0.3 on 2022-05-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0016_booktour_send_mail_alter_tour_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='travelapp.typeofpayment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rate',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='travelapp.tour'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'news')},
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('user', 'tour')},
        ),
    ]
