# Generated by Django 4.0.3 on 2022-05-09 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0018_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeConfirm',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code', models.IntegerField(default=0)),
            ],
        ),
    ]
