# Generated by Django 4.0.3 on 2022-05-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0019_codeconfirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeconfirm',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
