# Generated by Django 4.0.3 on 2022-05-12 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0020_alter_codeconfirm_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travelapp.news')),
            ],
        ),
    ]
