# Generated by Django 4.0.3 on 2022-05-12 13:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0024_alter_imagetour_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetour',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
