# Generated by Django 4.0.3 on 2022-05-16 12:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0025_alter_imagetour_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, null=True, verbose_name='image'),
        ),
    ]
