# Generated by Django 4.0.3 on 2022-05-18 05:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0027_user_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, null=True, verbose_name='image'),
        ),
    ]
